const { User } = require('../lib/user');
const uuidv4 = require('uuid/v4');

describe('user tests', () => {
  test('User has id, name, email, and password', () => {
    const user = new User('cara', 'email@email.com', 'password');
    expect(user).toEqual({ name: 'cara', email: 'email@email.com', password: 'password', id: 'test'});
  });

  test('User has id generated by uuid', () => {
    const user = new User('cara', 'email@email.com', 'password');
    expect(user.id).toEqual(uuidv4());
  });

  test('returns name and email to string', () => {
    const user = new User('cara', 'email@email.com', 'password');
    expect(user.toString()).toEqual('cara | email@email.com');
  });


});
